### ISSUE TITLE
【Bug】空白博客时，会显示错误信息

### ISSUE THREAD

**Issue by yaolifeng0629** [mazzzystar/tinymind#11]
![Clip_2024-09-22_12-12-42](https://github.com/user-attachments/assets/ba922867-a362-4389-bde1-0cad2ece968c)

**Comment by mazzzystar** [comment]
但是空白博客你是如何发布的呢，空白时好像无法点发布按钮。

**Comment by yaolifeng0629** [comment]
@mazzzystar 登录后，还没进行任何操作，切换到 博客 tab 就出现这个问题了

**Comment by mazzzystar** [comment]
啊我明白你的意思了！是如果从未创建博客，页面会显示错误信息对吗？
刚刚的commit应该修复了: https://github.com/mazzzystar/tinymind/commit/ab34c2a78b5517b078d91cb4428fb0eb4a30e86c

**Comment by yaolifeng0629** [comment]
@mazzzystar 对的，👍
