### ISSUE TITLE
增加导出功能

### ISSUE THREAD

**Issue by Vitowong00** [mazzzystar/tinymind#20]
数据都存在了GitHub中了，但是文本的格式不太友好。

如果要导出这些数据？有更好的方式吗？

**Comment by mazzzystar** [comment]
![](https://github.com/user-attachments/assets/eb1b5968-f41d-4421-9147-20fdfb21bd42)

我不确定你希望导出成怎样的格式，但最简单的事直接下载你的repo: https://github.com/Vitowong00/tinymind-blog

**Comment by Vitowong00** [comment]
导出 「博客」 「想法」 为 Markdown 文件？ 或者 只是 “content”
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/34e36e93-d52e-414d-93ad-0dee10bbeef3">
timestamp 好像不是 北京时间。


如果直接下载repo 的话，导出内容后，还要在进行 整理筛选出 “content”
<img width="782" alt="image" src="https://github.com/user-attachments/assets/127adc31-5b99-4bfa-8282-b35267e5ac6e">

**Comment by metrue** [comment]
导出的本质是为了“再使用”， JSON 也算很友好的适配格式了.

如果真是纯想本地使用而导出，生成整个静态网站也许是另一种“导出”.

**Comment by mazzzystar** [comment]
请看这个：https://github.com/gildas-lormeau/SingleFile 也许对你有用
Source：https://x.com/vikingmute/status/1839845550650536012
