### ISSUE TITLE
BUG: New Blog and Thoughts fail to display

### ISSUE THREAD

**Issue by triilman25** [mazzzystar/tinymind#26]
When I open my blog as a user not as a writer this bug happen. My new post on *blog* and *thoughts* can't be displayed except the old one. It also happens when we move between blog and thoughts. When we refresh the tab it'll become normal.

**Comment by mazzzystar** [comment]
I also noticed that issue and refreshing can get the latest blog & thoughts. I'll check it out today.

**Comment by mazzzystar** [comment]
This issue should have been fixed by [this commit](https://github.com/mazzzystar/tinymind/commit/38e3d3302cb2265beab82784dbbdc366b1108c92).

**Comment by triilman25** [comment]
It solved. Thanks for your fast response.

**Comment by triilman25** [comment]
that commit, I think make another bug. I can't edit my old or latest blog but thoughts is still normal.

**Comment by triilman25** [comment]
the blank tab that happen when I click the link as a writer.
