### ISSUE TITLE
这玩意也算博客吗

### ISSUE THREAD

**Issue by EchoZap** [mazzzystar/tinymind#29]
我自己写的必须得登录才能看，这叫哪门子博客？别人访问也看不了你写的东西啊

**Comment by mazzzystar** [comment]
<img width="1416" alt="image" src="https://github.com/user-attachments/assets/8708b5d7-69f4-4e9e-aaa6-46edb216f2e9">
我能匿名看到你的。

**Comment by EchoZap** [comment]
> <img alt="image" width="1416" src="https://private-user-images.githubusercontent.com/6824141/389418285-8708b5d7-69f4-4e9e-aaa6-46edb216f2e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTk1MTQsIm5iZiI6MTczMjUxOTIxNCwicGF0aCI6Ii82ODI0MTQxLzM4OTQxODI4NS04NzA4YjVkNy02OWY0LTRlOWUtYWFhNi00NmVkYjIxNmYyZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMDcyMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU1NDFmNGQxZGJkMTllNjU1MjI4NzU3OTJiMjk2YzE1Y2Y2ZjhkMmQ1Y2Q0MDIyZjljYzg4NzNmMTM4OGE2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ohECUvnDJWJsbdlwtaEGqnNwpxmmKFq_WFxiTCxWqRs"> 我能匿名看到你的。

可是为什么我使用手机浏览器访问我的地址，在不登录 github 的情况下，其会自动转化为“https://tinymind.me/unavailable”
![Uploading Screenshot_2024_1125_152115.png…]()

**Comment by mazzzystar** [comment]
你的截图也给出答案了，你没开VPN
 
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/7ca09963-535e-469a-aba7-1998d7dd8f1b">

**Comment by EchoZap** [comment]
> 你的截图也给出答案了，你没开VPN
> 
> <img alt="image" width="1109" src="https://private-user-images.githubusercontent.com/6824141/389420176-7ca09963-535e-469a-aba7-1998d7dd8f1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTk3NDcsIm5iZiI6MTczMjUxOTQ0NywicGF0aCI6Ii82ODI0MTQxLzM4OTQyMDE3Ni03Y2EwOTk2My01MzVlLTQ2OWEtYWJhNy0xOTk4ZDdkZDhmMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMDcyNDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE0NzczMTAwM2E1OGVjMDc5NGI3MTM3Yzg4OTAyNmIwOTZmMTEwZTU3ZjFlZThkOWFhOWViNzk3N2UzOTdmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zrcndqtv7JEekca3-3DGRKHHzuPFlQ9Ws27alsVxlEU">

哇，不好意思，我就是想找个能在国内访问的😂

**Comment by mazzzystar** [comment]
OK，作为个人我没办法、也不希望在这个网页上加入审查，所以这玩意在国内几乎不可能存活，抱歉了。

**Comment by EchoZap** [comment]
> OK，作为个人我没办法、也不希望在这个网页上加入审查，所以这玩意在国内几乎不可能存活，抱歉了。

怪不得我说电脑可以访问，手机就死活不行呢😂😂
