### ISSUE TITLE
Render Markdown contents

### ISSUE THREAD

**Issue by albedo-geo** [mazzzystar/tinymind#4]
Currently the thoughts will show the Markdown contents in its raw code. It would be much better if the thoughts support Markdown syntax.

**Comment by mazzzystar** [comment]
Hi, I'm aware of this issue. I'll try to work on it today!

**Comment by mazzzystar** [comment]
<img width="1248" alt="image" src="https://github.com/user-attachments/assets/7f435d9b-719b-485f-a0c9-e6d581e96120">
Thoughts now support Markdown.
