### ISSUE TITLE
Adding a license to a repository

### ISSUE THREAD

**Issue by metrue** [mazzzystar/tinymind#9]
For the long term maintenance, I would suggest we have a license for the repository.

**Comment by mazzzystar** [comment]
Hi, I'm not sure which open source license is more suitable for this project. Do you have any suggestions?

**Comment by metrue** [comment]
It's really up to you, I usually check this website for reference.
https://choosealicense.com/

If you don't care that much and hope it simple, MIT is quick choice.

**Comment by mazzzystar** [comment]
added MIT license.
